### ISSUE TITLE
on_guild_emojis_update() in bot.py not working properly

### ISSUE THREAD

**Issue by fuenix86** [hitomi-team/DNN#1]
When new emojis are uploaded/changed in one server, the bot's emoji cache does not update with it while running. The function also only appends emojis, so if one is removed from a server this won't match what the bot has.

I don't have much experience so I have something wrong feel free to correct me or ignore this issue :)

**Comment by harubaru** [comment]
The function should work with new emojis now, but I'll definitely go over and implement removing emojis from a cache when an emoji is removed.

**Comment by MeaninglessCode** [comment]
This should have been resolved in #2.
