### ISSUE TITLE
Not functional

### ISSUE THREAD

**Issue by dominic-03** [hitomi-team/DNN#3]
The bot does not work, unless I am using it wrong. I've tried giving it the same permissions as NQN as well as administrator permissions but it does not respond to any emojis. The console shows no errors.

If it is supposed to be used in a different way than NQN, that could be the problem too. But I don't see any commands that it accepts.

**Comment by harubaru** [comment]
Are you running the bot locally or are you using the bot that we are hosting? If it is the former, the bot should have proper permissions if no errors are visible.

**Comment by dominic-03** [comment]
I am hosting it myself (on a Raspberry Pi with Raspbian). I already gave it these permissions: https://discordapi.com/permissions.html#1610959936

**Comment by dominic-03** [comment]
Sorry, I copied the wrong link, these were the actual permissions: https://discordapi.com/permissions.html#1610968128

**Comment by harubaru** [comment]
Has the bot been invited to servers that you are trying to use emojis from?

**Comment by dominic-03** [comment]
> Has the bot been invited to servers that you are trying to use emojis from?

No, however the emojis I'm trying to use were previously sent in the server. I believe this worked OK with NQN, but if it doesn't work with DNN then that would be the problem.

**Comment by harubaru** [comment]
The bot only resolves emojis from servers that it is in, but it does not resolve emojis previously sent in message history.

**Comment by dominic-03** [comment]
That would be the problem then. Thanks for your help.
